
package Proyecto2;

import src.*;
import java.awt.Font;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.util.Iterator;
import javax.swing.JOptionPane;


/**
 *
 * @author nestor2502
 */
public class Ventana1 extends javax.swing.JFrame {
    
    public String frase2="";
    ManejoDocumentos m2;
    Lista <String> rutas;
    int seleccion;
    int cont =0;
    int noDocumentos=0;
    int noDocumentos2=0;
    int i=0;
    Ventana3 v3;
    int agrego =0;

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Proyecto 2");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLayout(null);
        v3 = new Ventana3();
         ingresados.removeAllItems();
         rutas = new Lista<String>();
        
        
        
        
     TextPrompt placeholder = new TextPrompt("Ingresa una frase", frase);
     placeholder.changeAlpha(0.75f);
         placeholder.changeStyle(Font.ITALIC);
         
          TextPrompt place = new TextPrompt("c :/. . . / . . . / . . . ", rutaDoc);
     place.changeAlpha(0.75f);
         place.changeStyle(Font.ITALIC);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        ingresar1 = new javax.swing.JButton();
        frase = new javax.swing.JTextField();
        documento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ingresados = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rutaDoc = new javax.swing.JTextField();
       // jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ingresar1.setText("Ingresar ");
        ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar1ActionPerformed(evt);
            }
        });

        frase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fraseActionPerformed(evt);
            }
        });

        documento.setText("Añadir documento");
        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Documentos Ingresados : ");

        ingresados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ingresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresadosActionPerformed(evt);
            }
        });

        jButton1.setText("Mostrar coincidencias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nueva consulta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        rutaDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaDocActionPerformed(evt);
            }
        });

        

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(rutaDoc)
                        .addGap(18, 18, 18)
                        .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(ingresados, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(frase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(120, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        .addGap(68, 68, 68))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(rutaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                       // .addComponent(jButton3)
                        .addGap(8, 8, 8)))
                .addComponent(ingresados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void fraseActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
         
         if(frase.getText().equals("")==false){
         frase.setEnabled(false);
         String buscando = frase.getText();
         frase2 = frase.getText();
         m2 = new ManejoDocumentos(frase2);
         ingresar1.setEnabled(false);
         //ingresados.addItem(frase.getText());
         }
         
         
    }                                         

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {  

        //Ventana4 v4 = new Ventana4();
        //v4.setVisible(true);
        frase2="";
        frase.setText("");
        frase.setEnabled(true);
        ingresar1.setEnabled(true);
        ingresados.removeAllItems();
        //seleccion = v4.getSeleccion();
        
    }                                        

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {   
     String rutam = rutaDoc.getText().trim();                                       
        if(rutas.contiene(rutam)==false){
        //cont =0;
        if(rutaDoc.getText().equals("")==false ){//|| rutaDoc.getText()!= " "){
       // String rutam = rutaDoc.getText().trim();
        try {
             BufferedReader lector = new BufferedReader(new FileReader(rutam));
             
             lector.close();
             
             agregarDocumento(rutam);
             
         }

         catch(FileNotFoundException e){//No encontro el documento

             JOptionPane.showMessageDialog(null, "No se encontro el documento");
        
         }catch(IOException e){//Errores varios

             JOptionPane.showMessageDialog(null, "Hubo algun problema");
    }
     
        }}
    
    }                                         
    public void agregarDocumento(String documento){
         if(rutas.contiene(documento)==false){
         m2.agregaDocumento(documento);
         rutas.agregaInicio(documento);
         ingresados.addItem(documento);
         rutaDoc.setText("");
         noDocumentos++;
         cont++;
         agrego=0;
         ;}
         
        
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
       // Iterator <String> iterator = rutas.iterator();
        //if(frase.getText().equals("")== false){
        //while(iterator.hasNext()==true){
          //   m2.agregaDocumento(iterator.next());
             //System.out.println(iterator.next());
            // System.out.println();
        //}
        
        if(i==0){
        cont=noDocumentos;
        i++;
         }
        setSimilitud();
        agrego++;
         //m2.calculaSimilitud();
         //m2.ordenaDocumentos();

         //String [] a1= m2.getOrdenados();
         //for(int i =0; i< a1.length;i++){
           //   System.out.println(a1[i]);
         //}
       


    }

    public void setSimilitud(){
        String [] a1= new String[0];;
        if(agrego==0 ){
             m2.calculaSimilitud();
             m2.ordenaDocumentos();
             m2.pruebaSim();
             a1= m2.getOrdenados();
             v3.setOrdenados(a1);  

        }
        
        //v3.setOrdenados(a1);
        v3.setFrase(frase2);
        v3.setVisible(true);
    }                                        

    private void ingresadosActionPerformed(java.awt.event.ActionEvent evt) {                                           
       
        
      
    }                                          

    private void rutaDocActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton documento;
    private javax.swing.JTextField frase;
    private javax.swing.JComboBox<String> ingresados;
    private javax.swing.JButton ingresar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;

    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField rutaDoc;
    // End of variables declaration                   
}